version: '3.7'
services:
        jenkins:
                build: .
                container_name: jenkins
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - ~/jenkins:/var/jenkins_home
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /usr/bin/docker:/usr/bin/docker

        postgres:
                image: "postgres"
                container_name: sonar-postgres
                ports:
                        - "5432:5432"
                
                environment:
                        - POSTGRES_USER=${POSTGRES_USER}
                        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

        sonar:
                image: "sonarqube"
                container_name: sonar
                ports:
                        - "9000:9000"

                environment:
                        - SONARQUBE_JDBC_URL=${SONARQUBE_JDBC_URL}
                        - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD}
                        - SONARQUBE_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME}

                depends_on: 
                        - postgres
volumes:
      jenkins:
